# =============================================================================
# daba - Kubernetes Namespace
# =============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: daba
  labels:
    name: daba
    environment: production
